// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/gravatar/gravatar.d.ts
declare namespace GravatarModule {
  type Options = {
    d?: string
    default?: string
    f?: string
    forcedefault?: string
    r?: string
    rating?: string
    s?: string
    size?: string
  }

  function url(email: string, options?: Options, forceProtocol?: boolean): string;
}

declare module "gravatar" {
    export = GravatarModule;
}
